import React, { useState } from 'react';
import { getPhonesPagination } from '../../api/phones';
import { Pagination } from '../../components/pagination/Pagination';
import { Catalog } from '../../components/catalog/Catalog';
import { Phone } from '../../types/Phone';
import './Accessories.scss';

const defaultQuantity = '16';

const arr = [
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
  {
    id: 'string',
    category: 'string',
    phoneId: 'string',
    itemId: 'string',
    name: 'string',
    fullPrice: 234,
    price: 234,
    screen: 'string',
    capacity: 'string',
    color: 'string',
    ram: 'string',
    year: 234,
    image: 'string',
  },
];

export const Accessories = () => {
  const [accessoriesFromServer, setAccessoriesFromServer] = useState<Phone[]>(arr);
  const [currentPage, setCurrentPage] = useState('1');
  const [selectedSort, setSelectedSort] = useState<string | null>(null);
  const [selectedQuantity, setSelectedQuantity] = useState<string | null>(defaultQuantity);

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  async function getAccessoriesFromServer() {
    let accessories = await getPhonesPagination({
      page: currentPage,
      perPage: selectedQuantity ?? undefined,
      sort: selectedSort || 'Newest',
    });

    accessories = arr;

    setAccessoriesFromServer(accessories);
  }

  return (
    <div className="wrapper">
      <Catalog
        selectedPerPage={selectedQuantity}
        selectedSort={selectedSort}
        products={accessoriesFromServer}
        title="Mobile phones"
        onSortChange={(value) => setSelectedSort(value)}
        onQuantityChange={(value) => setSelectedQuantity(value)}
      />
      <Pagination
        totalCards={accessoriesFromServer.length}
        perPage={selectedQuantity || defaultQuantity}
        onPageChange={(value) => setCurrentPage(value.toString())}
        currentPage={currentPage}
      />

    </div>
  );
};
